### ISSUE TITLE
v0.6.5 - Stray closing brace } in completed signup form

### ISSUE THREAD

**Issue by Zorlin** [plugorgau/ugmm#15]
When a user signs up to UGMM, their name is displayed with a stray brace } in front of their name.

**Comment by Zorlin** [comment]
Closing issue as cannot reproduce...

**Comment by niceness** [comment]
Re-occured with user 10584 at `Date: Thu, 23 Oct 2025 18:06:11 +0800 (AWST)`

**Comment by jhenstridge** [comment]
From the nginx error log:

```
2025/10/23 18:08:28 [error] 561622#561622: *920133 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "memberOf" in /usr/share/plug-ugmm/lib/PLUG/Members.class.php on line 952; PHP message: PHP Warning:  Undefined array key "memberOf" in /usr/share/plug-ugmm/lib/PLUG/Members.class.php on line 952; PHP message: PHP Warning:  Undefined array key "memberOf" in /usr/share/plug-ugmm/lib/PLUG/Members.class.php on line 952" while reading response header from upstream, client: 60.241.73.43, server: ugmm.plug.org.au, request: "POST /signup HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "ugmm.plug.org.au", referrer: "https://ugmm.plug.org.au/"
```

That is this line:

https://github.com/plugorgau/ugmm/blob/9d82625404d17086f8ed8b0047e07558ee1def9f/lib/PLUG/Members.class.php#L952

Are we sure this is on the signup complete form? Anything actually in the LDAP tree should be a member of some group. If it is redisplaying the signup form after failing to validate some field, it might be this:

https://github.com/plugorgau/ugmm/blob/9d82625404d17086f8ed8b0047e07558ee1def9f/lib/PLUG/templates/signup.tpl#L65

Note the second close brace after `{if isset($newmember)}`.
