### ISSUE TITLE
Future of UGMM

### ISSUE THREAD

**Issue by luke-john** [plugorgau/ugmm#4]
What are our intentions for UGMM going into the future?

Possible options
- PLUG specific tool
  - advantages
    - heavy integration to plug infrastructure
- LUG specific tool
  - advantages
    - more potential developers
    - more potential users
- General Purpose community management tool
  - advantages
    - more potential developers
    - far more potential developers

What're other peoples thoughts on options/(dis)advantages?

**Comment by timwhite** [comment]
I think a LUG specific tool, but written as generic as possible.

What do we need?

- Simple database of users, including contact details, and membership status/expiry and payments
- Users can login and update details
- Admins can login and update details, and process payments

Discussion can continue in #3 whether central authentication off that database is required. Personally, if we don't need central auth off our members database, I'd use "Social Signin" off everything we can think of to get our members flexibility (Facebook, Google, GitHub).

**Comment by luke-john** [comment]
closing this issue as stale, while cleaning up my old github issues
