### ISSUE TITLE
Renewal Dates

### ISSUE THREAD

**Issue by HybridAU** [plugorgau/ugmm#9]
I recently renewed an account on UGMM for a member who's membership expired on 2016-06-13 but they had paid before they expired and we hadn't processed the payment.

The member made a payment on 2016-05-17 (27 days early),  I backdated the payment to the correct date. The new expiry date for the member was 2017-05-16 (364 days from payment) but it should have been 2017-06-13 (365 days from expiry date)

I think it should be (please excuse the pythonesque psudo code)

```Python
if expiry_date > payment_date:
    expiry_date = expiry_date + 1 year
else:
    expiry_date = payment_date + 1 year
```

I'm not great with PHP but I'll have a look at the source and see if I can figure out what's going on and how to change it.

**Comment by timwhite** [comment]
Fixed merged in
